{"template":"../src/Example/Example.page.js","sharedHashesByProp":{},"data":{"libraryName":"RxJS","exampleName":"onErrorResumeNext","example":{"name":"onErrorResumeNext","title":"onErrorResumeNext","files":[{"name":"./examples/rxjs/error-handling/onErrorResumeNext.js","ext":".js","content":"const { rxObserver } = require('api/v0.3');\nconst { timer, onErrorResumeNext, throwError, of } = require('rxjs');\nconst { concat, ignoreElements } = require('rxjs/operators');\n\n\nconst failTimer$ = timer(5).pipe(\n    ignoreElements(),\n    concat(throwError('Ouch!'))\n  );\n\nconst fineTimer$ = timer(5).pipe(\n    ignoreElements(),\n    concat(of('Ok!'))\n  );\n\nconst strategicTimer$ = onErrorResumeNext(\n    failTimer$,\n    fineTimer$\n  );\n\nfailTimer$.subscribe(rxObserver('fail timer'));\nfineTimer$.subscribe(rxObserver('fine timer'));\nstrategicTimer$.subscribe(rxObserver('strategic'));"},{"name":"./examples/rxjs/error-handling/afterword.md","ext":".md","content":"Check out [\"Error handling in RxJS\"](https://medium.com/@kddsky/error-handling-in-rxjs-bac0f96a7def) article to get better understanding how not to fail with Observables."}]}},"path":"rxjs/onErrorResumeNext"}
