{"template":"../src/Example/Example.page.js","sharedHashesByProp":{},"data":{"libraryName":"RxJS","exampleName":"catch","example":{"name":"catch","title":"catch","pageTitle":"RxJS catch operator example with a marble diagram","desc":"","docsUrl":"https://rxjs.dev/api/operators/catch","editUrl":"https://github.com/observable-playground/observable-playground/tree/master/src/examples/rxjs/catch.md","content":"\n\n```js\nconst { rxObserver } = require('api/v0.3');\nconst { timer, throwError, of } = require('rxjs');\nconst { switchMap, catchError } = require('rxjs/operators');\n\nconst error$ = timer(5).pipe(\n    switchMap(() => throwError('oh'))\n  );\n  \nconst catch$ = error$.pipe(\n    catchError(err => of(err))\n  );\n\n\nerror$.subscribe(rxObserver());\ncatch$.subscribe(rxObserver());\n\n```\n\nCheck out [\"Error handling in RxJS\"](https://medium.com/@kddsky/error-handling-in-rxjs-bac0f96a7def) article to get better understanding how not to fail with Observables."}},"path":"rxjs/catch"}
