{"template":"../src/Example/Example.page.js","sharedHashesByProp":{},"data":{"libraryName":"RxJS","exampleName":"catch","example":{"name":"catch","title":"catch","files":[{"name":"./examples/rxjs/error-handling/catch.js","ext":".js","content":"const { rxObserver } = require('api/v0.3');\nconst { timer, throwError, of } = require('rxjs');\nconst { switchMap, catchError } = require('rxjs/operators');\n\nconst error$ = timer(5).pipe(\n    switchMap(() => throwError('oh'))\n  );\n  \nconst catch$ = error$.pipe(\n    catchError(err => of(err))\n  );\n\n\nerror$.subscribe(rxObserver());\ncatch$.subscribe(rxObserver());"},{"name":"./examples/rxjs/error-handling/afterword.md","ext":".md","content":"Check out [\"Error handling in RxJS\"](https://medium.com/@kddsky/error-handling-in-rxjs-bac0f96a7def) article to get better understanding how not to fail with Observables."}]}},"path":"rxjs/catch"}
