{"template":"../src/Example/Example.page.js","sharedHashesByProp":{},"data":{"libraryName":"RxJS","exampleName":"throwError","example":{"name":"throwError","title":"throwError","pageTitle":"RxJS throwError function example + marble diagram","desc":"","docsUrl":"https://rxjs.dev/api/index/function/throwError","editUrl":"https://github.com/observable-playground/observable-playground/tree/master/src/examples/rxjs/throwError.md","content":"\n\n```js\nconst { rxObserver } = require('api/v0.3');\nconst { timer, throwError } = require('rxjs');\nconst { switchMap } = require('rxjs/operators');\n\ntimer(10)\n  .pipe(\n    switchMap(()=>\n      throwError('Err!')\n    )\n  )\n  .subscribe(rxObserver());\n\n```\n\nCheck out [\"Error handling in RxJS\"](https://medium.com/@kddsky/error-handling-in-rxjs-bac0f96a7def) article to get better understanding how not to fail with Observables."}},"path":"rxjs/throwError"}
