{"template":"../src/Example/Example.page.js","sharedHashesByProp":{},"data":{"libraryName":"RxJS","exampleName":"throwError","example":{"name":"throwError","title":"throwError","files":[{"name":"./examples/rxjs/error-handling/throwError.js","ext":".js","content":"const { rxObserver } = require('api/v0.3');\nconst { timer, throwError } = require('rxjs');\nconst { switchMap } = require('rxjs/operators');\n\ntimer(10)\n  .pipe(\n    switchMap(()=>\n      throwError('Err!')\n    )\n  )\n  .subscribe(rxObserver());"},{"name":"./examples/rxjs/error-handling/afterword.md","ext":".md","content":"Check out [\"Error handling in RxJS\"](https://medium.com/@kddsky/error-handling-in-rxjs-bac0f96a7def) article to get better understanding how not to fail with Observables."}]}},"path":"rxjs/throwError"}
