{"template":"__react_static_root__/src/Example/Example.page.js","sharedHashesByProp":{},"data":{"libraryName":"RxJS","exampleName":"throwError","example":{"name":"throwError","title":"throwError","pageTitle":"RxJS throwError function example + marble diagram","desc":"throwError creates an Observable, that will immediately emit an error","docsUrl":"https://rxjs.dev/api/index/function/throwError","editUrl":"https://github.com/observable-playground/observable-playground/tree/master/src/examples/rxjs/throwError.md","content":"\n\nthrowError creates an Observable, that will immediately emit an error  \nIn the example below a value on [timer](/rxjs/timer/) will be [substituted](/rxjs/switchMap/) with a `throwError` stream at 10ms:\n\n```js\nconst { rxObserver } = require('api/v0.3');\nconst { timer, throwError } = require('rxjs');\nconst { switchMap } = require('rxjs/operators');\n\ntimer(10).pipe(\n    switchMap(()=>\n      throwError('Err!')\n    )\n  )\n  .subscribe(rxObserver());\n\n```\n\nCheck out [\"Error handling in RxJS\"](https://medium.com/@kddsky/error-handling-in-rxjs-bac0f96a7def) article to get better understanding how not to fail with Observables.\n"}},"path":"rxjs/throwError"}
